name: Release

on:
  # Déclenche le workflow lors de la création d'un tag
  push:
    tags:
      - 'v*.*.*'  # Exemple: v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (exemple avec Node.js, mais adapte selon ton environnement)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Créer la release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Ajouter les fichiers à la release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/my-asset.zip  # Remplace par le chemin de ton fichier
          asset_name: my-asset.zip
          asset_content_type: application/zip
